### ISSUE TITLE
MOLGENIS Docker does not work in Ubuntu 16.04 and 17.04

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/docker#17]
### How to Reproduce
- Install Ubuntu 16.04 (LTS version)
- Install Docker community version according to the instruction from Docker https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/
- clone the MOLGENIS docker git repository
- follow the instruction in the readme to run MOLGENIS

### Expected behavior
- The 4 containers for MOLGENIS are all running and MOLGENIS is accessible on http:/localhost:8081/

### Observed behavior
- MOLGENIS is not accessible
- ElasticSearch container is not running, it aborts after approximately 50 seconds

### Sytem details
Ubuntu 16.04: Docker version 17.06.0-ce, build 02c1d87
Ubuntu 17.04: Docker version 17.04.0-ce, build 4845c56

**Comment by fdlk** [comment]
This sounds familiar, possibly related to https://github.com/travis-ci/travis-ci/issues/6534
Could you try running `sudo sysctl -w vm.max_map_count=262144` ?

**Comment by djvanenckevort** [comment]
That indeed solves the issue. This should be clearly mentioned in the documentation.
