### ISSUE TITLE
molgenis local host home page empty

### ISSUE THREAD

**Issue by bansell** [molgenis/docker#35]
I'm trying to run the NGS_RNA pipeline.

I have installed and composed the molgenis docker, and access the localhost:8081 in Firefox via X11, CentOS 7.

The http://localhost:8081/menu/main/home page is empty aside from the Sign In button. What is the expected behaviour for this page?
[dockerBuild.out.txt](https://github.com/molgenis/docker/files/2281815/dockerBuild.out.txt)

**Comment by fdlk** [comment]
This looks better now in molgenis 8
