### ISSUE TITLE
version 8.1 is broken

### ISSUE THREAD

**Issue by fjrmoreews** [molgenis/docker#50]
when running docker compose up, 
the version 8.1 does not start correctly :
molgenis_1       | Exception in thread "schedulerFactoryBean_Worker-1" java.lang.NoClassDefFoundError: ch/qos/logback/core/status/WarnStatus
molgenis_1       | 	at ch.qos.logback.classic.LoggerContext.noAppenderDefinedWarning(LoggerContext.java:186)

no problem with version 8

**Comment by fdlk** [comment]
@fjrmoreews I cannot reproduce over here. What sometimes happens is that volumes or images do not get cleaned up properly. Could you try thorougly cleaning things up as described [in the README](https://github.com/molgenis/docker/blob/master/README.md#remove-installation)?

**Comment by fjrmoreews** [comment]
I found the issue : after git pull , the .env was updated  ( molgenis/8.1/.env)
TAG=8.1.1  => TAG=8.1.7
8.1.7  docker image runs fine.
cheers
FM

**Comment by fdlk** [comment]
@fjrmoreews thanks for the update!
